Update packages with osbuild and blueprint package list and dependencies
osbuild/automotive-ci pull request #123
Opened 2021-07-27 08:02 UTC by RajeshKumarSrivastava

This list consists of the packages discussed with QE team.
It has all packages that osbuild uses internally and the packages in blueprint including their dependencies resolved though the content resolver.

2021-07-27 10:47 UTC, lioramilbaum approved these changes

2021-07-27 10:48 UTC, lioramilbaum requested changes
Please close the PR

2021-07-27 10:48 UTC, HubertStefanski requested changes
Let's close this one off in favour of the PR submitted from the non-fork

2021-07-28 07:49 UTC, RajeshKumarSrivastava commented
closing the PR , similar is opened in a  branch on main

2021-07-28 08:33 UTC, closed without merging